// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qjprfsdducpkxeezzvst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqcHJmc2RkdWNwa3hlZXp6dnN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNzAxNDcsImV4cCI6MjA2Njk0NjE0N30.B9UO9Sn1jwmLQdoZDhu0YdFRBhhRSu5d1Heyzaq7WLY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});